#define NEW_EFFECT(INSTRUMENT_NAME'WET_ROUTE'DRY_ROUTE'WET_AMOUNT'DRY_AMOUNT'GLOBALS'BODY) #
  $EFFECT_BYPASS_DEP($INSTRUMENT_NAME'$DRY_ROUTE'$WET_ROUTE'$WET_AMOUNT'$DRY_AMOUNT)

  $GLOBALS

  instr $INSTRUMENT_NAME
    $BODY
  endin

  $MIXER_CHANNEL($INSTRUMENT_NAME)
#
