#include "DrumLoop1.orc"
#include "VerseLoop.orc"
#include "CleanLoop.orc"
#include "DrumCut.orc"
#include "FilterSweep.orc"
#include "PianoInterrupt.orc"
#include "ChorusDrumLoop.orc"
#include "ChorusLoop.orc"
#include "ChorusFluteLoop.orc"

; Sections
#include "Verse.orc"
#include "DelayBridge.orc"
#include "Bridge.orc"
#include "ChorusSegue.orc"
#include "Chorus.orc"
#include "Outro.orc"
