#include "MachineSickness.orc"
#include "CloudThoughts.orc"
#include "BreezeNudge.orc"
#include "Voidlessness.orc"
#include "DrumKit.orc"
#include "../../../instruments/LayeredBassSynth.orc"
#include "TwistedUpHatExample.orc"
