#include "DrumPattern1.orc"
#include "GrowlOnPattern1.orc"
#include "TwinklePattern1.orc"
#include "TwinkleMelodyLong.orc"
#include "TwinkleMelodyShort.orc"
#include "Twinkle2CounterMelodyShort.orc"
#include "TwinklePattern3.orc"
#include "BassLine1.orc"
