#include "LinnDrumCabasa.orc"
#include "LinnDrumClap.orc"
#include "LinnDrumClosedHat.orc"
#include "LinnDrumCowbell.orc"
#include "LinnDrumCrash.orc"
#include "LinnDrumKick.orc"
#include "LinnDrumOpenHat.orc"
#include "LinnDrumRide.orc"
#include "LinnDrumRim.orc"
#include "LinnDrumSnare.orc"
#include "LinnDrumTambourine.orc"
#include "LinnDrumTom.orc"

#include "LinnDrumKitBus.orc"
#include "LinnDrumKitReverb.orc"
#include "LinnDrumKitDistortion.orc"
