#include "Kick/Kick.orc"
#include "Snare/Snare.orc"
#include "ClosedHat/ClosedHat.orc"
#include "OpenHat/OpenHat.orc"
#include "Crash/Crash.orc"
#include "HatPedal/HatPedal.orc"

#include "Photoshop/Photoshop.orc"
#include "PhotoshopSamples/PhotoshopSamples.orc"
#include "PunishmentAwaits/PunishmentAwaits.orc"
#include "PunishYou/PunishYou.orc"

#include "Vocals/EndingVocal.orc"
#include "Vocals/SegueVocal.orc"
#include "Vocals/VerseOne.orc"
#include "Vocals/VerseTwo.orc"
#include "Vocals/VocalEffectChain/VocalEffectChain.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainCompressor.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainDelay.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainDistortion.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainFreezer.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainLowPassFilter.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainMultiStageDistortion.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainPitchShifter.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainReverb.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainRingMod.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainTremolo.orc"
#include "Vocals/VocalEffectChain/VocalEffectChainWarmDistortion.orc"
