#include "CharybdisLoop1.orc"
#include "DelayForCharybdisLoop1.orc"
#include "CharybdisLoop2.orc"
#include "Stab.orc"
#include "RaspingTone.orc"
#include "ChorusForRaspingTone.orc"
#include "DustyBass.orc"
#include "DustyBassGrain.orc"
#include "DelayForDustyBassGrain.orc"

